name: Leaf-Lens Backend CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Create .env file
        run: |
          cd backend
          echo "MONGO_URI=mongodb://localhost:27017" > .env
          echo "FLASK_ENV=testing" >> .env
          
      - name: Lint with flake8
        run: |
          cd backend
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          
      - name: Run tests
        run: |
          cd backend
          # Add your test command here, e.g.:
          # python -m pytest tests/

  deploy:
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn
          
      # For Heroku deployment
      - name: Deploy to Heroku
        if: false  # Change to true when ready to deploy
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "leaf-lens-api"  # Change to your app name
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
        env:
          HD_MONGO_URI: ${{ secrets.MONGO_URI }}
          HD_EMAIL_USER: ${{ secrets.EMAIL_USER }}
          HD_EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          
      # For custom server deployment
      - name: Deploy to custom server
        if: false  # Change to true when ready to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deployment
            git pull
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            # Create or update .env file
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
            # Restart the service
            sudo systemctl restart leaf-lens-api 